## 1) Catch
Check the typos...


## 2) Solution:
Trying to call the function "Fallout" will result into a failure. Instead it is needed
to call the "Fal1out" function. If you don't catch this, pay more attention to each letter...

    await contract.Fal1out({value: 1})
    

